- name: Install NOC
  hosts: svc-noc-exec
  become: yes
  any_errors_fatal: false
  gather_facts: True
  tags:
    - node
    - noc
  vars_files:
    - "../../vars/main.yml"
    - "../../vars/{{ ansible_distribution }}.yml"
  roles:
    - role: custom